apiVersion: v1
description: A Kubernetes controller designed to solve running and auto-managing Habitat services on Kubernetes.
engine: gotpl
maintainers:
  - name: Zeeshan Ali
    email: zeeshan@kinvolk.io
name: habitat-operator
sources:
  - https://github.com/kinvolk/habitat-operator
version: 0.4.0
