apiVersion: v1
kind: Secret
metadata:
  name: user-toml-secret
type: Opaque
data:
  # Each item needs to be encoded in base64, as Kubernetes expects that encoding.
  # Plain text content of the secret: "port = 6666"
  # This overrides the port set in the postgresql Habitat service.
  user.toml: cG9ydCA9IDY2NjY=
