apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "habitat-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: habitat
    release: {{ .Release.Name }}
  name: {{ template "habitat-operator.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "habitat-operator.name" . }}
        operator: habitat
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "habitat-operator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
          {{- if .Values.kubeletService.enable }}
            - --kubelet-service={{ .Values.kubeletService.namespace }}/{{ .Values.kubeletService.name }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "habitat-operator.fullname" . }}
    {{- end }}
